admin_apps/config/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^', include('mileage.urls', namespace="mileage")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

admin_apps/mileage/urls.py
from django.conf.urls import patterns, url, include, handler404
from mileage import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = patterns ('',
    url(r'^$', views.ReimbursementListView.as_view(), name="home"),
    url(r'^r/create$', views.ReimbursementCreateView.as_view(), name="create_reimbursement"),
    url(r'^del/(?P<pk>\d+)$', views.TripDeleteView.as_view(), name='delete_trip'),
    url(r'^r/(?P<pk>\d+)$', views.TripListView.as_view(), name='detail_reimbursement'),
    url(r'^del/r/(?P<pk>\d+)$', views.ReimbursementDeleteView.as_view(), name='delete_reimbursement'),
    ) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

admin_apps/templates/base.html
{% load staticfiles %}
<!DOCTYPE>
<html>
<head>
    <title>{% block title %}BACI Mileage{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, user-scalable=no" />
    <!--Bootstrap and Font Awesome Stuff -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    </script></script>

    <!--extra js stuff-->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.1.3/css/jasny-bootstrap.min.css">
    <script src="//cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.1.3/js/jasny-bootstrap.min.js"></script>
    <script src="{% static "bootstrap-switch.min.js" %}"></script>
    <script src="{% static "footable.js" %}"></script>

    
    <!-- Custom CSS -->
    <link rel="stylesheet" type="text/css" href="{% static "style.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "footable.core.min.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "bootstrap-switch.min.css" %}">
    {{ form.media }}

</head>
<body>
     <!-- Fixed navbar -->

        <div class="nav-padding-top navmenu navmenu-default navmenu-fixed-left offcanvas-sm">
          <a class="navmenu-brand visible-md visible-lg" href="{% url 'mileage:home' %}">BACI Mileage Reimbursement <small>Logged in as {{user.email}}</small></a>
          <ul class="nav navmenu-nav">
            <li><a href="{% url 'account_logout' %}"><div class="btn btn-default">Logout</div></a></li>
            <li><a href="{% url 'mileage:create_reimbursement' %}"><div class="btn btn-default">New Reimbursement</div></a></li>
            <li><a style="color:#000;">Reimbursements</li></a>
            {% block reimbursements %}{% endblock %}
          </ul>
        </div>

    <div class="navbar navbar-default navbar-fixed-top hidden-md hidden-lg">
      <button type="button" class="navbar-toggle" data-toggle="offcanvas" data-target=".navmenu">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'mileage:home' %}">BACI Mileage Reimbursement</small></a>
    </div>
        {% if messages %}
            <ul style="list-style:none; padding-left:0; margin-bottom:0px;" class="messages">
                {% for message in messages %}
                  <li{% if message.tags %} style="margin-bottom:0px" class="alert alert-fixed-top alert-{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}


            {% block info %}{% endblock %}
            {% block head %} {% endblock %}
            {% block content %}{% endblock %}
            

</body>
</html>
<script>
window.setTimeout(function() {
    $(".alert").fadeTo(500, 0).slideUp(500, function(){
        $(this).remove(); 
    });
}, 2000);
</script>