admin_apps/config/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^', include('mileage.urls', namespace="mileage")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

admin_apps/mileage/urls.py
from django.conf.urls import patterns, url, include, handler404
from mileage import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = patterns ('',
    url(r'^$', views.ReimbursementListView.as_view(), name="home"),
    url(r'^r/create$', views.ReimbursementCreateView.as_view(), name="create_reimbursement"),
    url(r'^del/(?P<pk>\d+)$', views.TripDeleteView.as_view(), name='delete_trip'),
    url(r'^r/(?P<pk>\d+)$', views.TripListView.as_view(), name='detail_reimbursement'),
    url(r'^del/r/(?P<pk>\d+)$', views.ReimbursementDeleteView.as_view(), name='delete_reimbursement'),
    ) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

admin_apps/mileage/models.py
# mileage.models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.core.exceptions import ValidationError
from django.utils import timezone
from django.db.models import Sum
from django.db.models.signals import post_save
from django.utils.text import slugify

import datetime


# Create your models here.
class TimeStampedModel(models.Model):
    """
    An abstract base class model that provides self-updating
    ``created`` and ``modified`` fields.
    """
    created = models.DateTimeField(default=datetime.datetime.now, editable=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

class Reimbursement(TimeStampedModel):

    staff = models.ForeignKey(User)
    department = models.CharField(max_length=25, blank=False)
    payperiod = models.CharField(max_length=25, blank=False)

    def __unicode__(self):
        return self.payperiod

    def get_absolute_url(self):
        return reverse('mileage:detail_reimbursement', kwargs={'pk': self.id})

class Trip(TimeStampedModel):
    """
    Staff will track a trip by it's odometer. They will record the beginning
    and the end of the odometer.
    """
    reimbursement = models.ForeignKey(Reimbursement)
    trip_date = models.DateTimeField()
    trip_begin = models.IntegerField(blank=False)
    trip_end = models.IntegerField(default=0)
    description = models.CharField(max_length=255, blank=False)
    amount_owed = models.DecimalField(max_digits=10, decimal_places=2, blank=True)
    distance = models.IntegerField(blank=True)

    def __unicode__(self):
        return self.description

    def save(self, *args, **kwargs):
        self.amount_owed = (self.trip_end - self.trip_begin)*0.45
        self.distance = (self.trip_end - self.trip_begin)
        super(Trip, self).save(*args, **kwargs)


    def get_delete_url(self):
        return reverse('mileage:delete_trip', kwargs={'pk': self.id})

admin_apps/mileage/forms.py
from django import forms 
from django.db import models
from django.core.exceptions import ValidationError
from django.forms.models import inlineformset_factory

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Div, HTML, Field, Fieldset, Submit, Layout, ButtonHolder
from crispy_forms.bootstrap import StrictButton
from datetimewidget.widgets import DateTimeWidget

from mileage.models import Trip, Reimbursement

class ReimbursementForm(forms.ModelForm):
    class Meta:
        model = Reimbursement
        exclude = ('user','slug')

    def __init__(self, *args, **kwargs):
        super(ReimbursementForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = 'form-horizontal'
        self.helper.layout = Layout(
            Fieldset(
                Field('payperiod', css_class="col-lg-6 mileage-input"),
                Field('department', css_class="col-lg-6 mileage-input"),
            ButtonHolder (
                Submit('add', 'Add', css_class='btn-primary pull-right')
                )
            ) 
        )

class TripForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(TripForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = 'form-horizontal'
        self.helper.form_show_labels = False
        self.helper.layout = Layout(
            Field('trip_begin', type="number", placeholder="Record your starting mileage", css_class="col-md-6"),
            Field('trip_end', type="number", placeholder="Record your ending mileage", css_class="mileage-input"),
            Field('description', css_class="mileage-input"),
            HTML("<h4 style='padding-left:12px;'><small>*If using an odometer, record 0.</small></h4>"),
            ButtonHolder (
                Submit('next', 'Next', css_class='btn-primary pull-right')
                )
            )

    def clean(self):
        super(TripForm, self).clean()
        cleaned_data = self.cleaned_data
        trip_data = cleaned_data.get('trip_begin')
        if trip_data < 0:
            raise ValidationError("Beginning Mileage cannot be negative.")
        return cleaned_data

    class Meta:
        widgets = {
            #Use localization and bootstrap 3
            'trip_date': DateTimeWidget(attrs={'id':"date_time"}, usel10n = True, bootstrap_version=3)
        }
        model = Trip
        fields = ['trip_date', 'trip_begin', 'trip_end', 'description']

admin_apps/mileage/views.py
# mileage/views.py
from django.core.urlresolvers import reverse, reverse_lazy
from django.shortcuts import redirect
from django.template import RequestContext
from django.core.exceptions import PermissionDenied
from django.views import generic
from django.views.generic import detail
from django.db.models import Sum, Count, Max, Min
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.utils import timezone
from django.contrib.auth.models import User, Group
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render, render_to_response, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib import messages
from django.forms.models import inlineformset_factory
from django.forms.formsets import formset_factory
from django.contrib.auth.decorators import user_passes_test
from django.shortcuts import get_object_or_404
from django.views.generic.base import RedirectView


from braces import views
from extra_views import ModelFormSetView, InlineFormSetView
from formtools.wizard.views import SessionWizardView

from mileage.models import Trip, Reimbursement
from mileage.forms import TripForm, ReimbursementForm
from adapters import FormsetMixin, RequiredInlineFormSet, get_total_amount_owed, OwnershipMixin

class ReimbursementDetailView(DetailView):
    model = Reimbursement

    def dispatch(self, request, *args, **kwargs):
        object_owner = self.get_object()
        if object_owner.staff != self.request.user:
            return redirect('mileage:home')
        return super(ReimbursementDetailView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(ReimbursementDetailView, self).get_context_data(**kwargs)
        trips = Trip.objects.filter(reimbursement = self.object)
        #Other Context stuff
        reimbursement = Reimbursement.objects.filter(staff=self.request.user)
        context['total_owed'] = trips.aggregate(Sum('amount_owed'))
        context['total_travelled'] = trips.aggregate(Sum('distance'))
        context['reimbursements'] = reimbursement
        context['trips'] = trips
        context['form'] = TripForm
        return context

#Creation View for Staff
class TripAddView(
    views.FormValidMessageMixin,
    generic.CreateView):
    """
    Handles post() in for the TripList View. Allows addition of trips.
    """
    form_valid_message = "Trip successfully added."
    template_name = 'mileage/reimbursement_detail.html'
    model = Trip
    fields = ('trip_begin', 'trip_end', 'description', 'trip_date')

    def get_success_url(self):
        #redirects to edit to add trip end
        return reverse('mileage:detail_reimbursement', kwargs={'pk': self.kwargs['pk']})

    def form_valid(self, form):
        self.object = form.save(commit=False)
        reimbursement = Reimbursement.objects.get(pk=self.kwargs['pk'])
        self.object.reimbursement = reimbursement
        self.object.save()
        return super(TripAddView, self).form_valid(form)

class TripDeleteView(
    SuccessMessageMixin,
    RedirectView):
    
    def get_redirect_url(self, *args, **kwargs):
        trip = get_object_or_404(Trip, pk=kwargs['pk'])
        if trip.reimbursement.staff == self.request.user:
            self.url = trip.reimbursement.get_absolute_url()
            messages.add_message(self.request, messages.INFO, 'Trip Deleted')
            self.success_message = "Trip successfully deleted."
            trip.delete()
            return super(TripDeleteView, self).get_redirect_url(*args, **kwargs)
        else:
            self.url = reverse('mileage:home')
            messages.add_message(self.request, messages.INFO, 'Error. Redirected.')
            return super(TripDeleteView, self).get_redirect_url(*args, **kwargs)


class TripListView(
    views.LoginRequiredMixin,
    generic.View):
    """
    View that is sent to URLConf to split the class into two CBV
    """

    def get(self, request, *args, **kwargs):
        view = ReimbursementDetailView.as_view()
        return view(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        view = TripAddView.as_view()
        return view(request, *args, **kwargs)

class ReimbursementDeleteView(
    SuccessMessageMixin,
    RedirectView):

    
    def get_redirect_url(self, *args, **kwargs):
        reimbursement = get_object_or_404(Reimbursement, pk=kwargs['pk'])
        if reimbursement.staff == self.request.user:
            reimbursement.delete()
            messages.add_message(self.request, messages.INFO, 'Reimbursement Deleted.')
            return reverse('mileage:home')
        else:
            self.url = 'mileage:home'
            messages.add_message(self.request, messages.INFO, 'Error. Redirected.')
            return reverse('mileage:home')



class ReimbursementListView(ListView):

    model = Reimbursement
    def get_queryset(self):
        queryset = super(ReimbursementListView, self).get_queryset()
        queryset = queryset.filter(staff = self.request.user)
        return queryset

class ReimbursementCreateView(CreateView,
    views.FormValidMessageMixin):
    model = Reimbursement
    fields = ['payperiod', 'department']

    def get_context_data(self, **kwargs):
        context = super(ReimbursementCreateView, self).get_context_data(**kwargs)
        reimbursement = Reimbursement.objects.filter(staff=self.request.user)
        context['reimbursements'] = reimbursement
        return context

    def get_success_url(self):
        return reverse('mileage:detail_reimbursement', args=(self.object.id,))


    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.staff = self.request.user
        self.object.save()
        messages.add_message(self.request, messages.INFO, 'Reimbursement Created. Add some trips now!')
        return super(ReimbursementCreateView, self).form_valid(form)

admin_apps/templates/mileage/reimbursement_detail.html
{% extends "base.html" %}

{% block reimbursements %}
  {% for reimbursement in reimbursements %}
    <li><a href="{{reimbursement.get_absolute_url}}">{{ reimbursement.payperiod }}</a></li>
    {% endfor %}
{% endblock %}


{% block content %}
{% load crispy_forms_tags %}

<div class="container" style="display:table; width: 100%;">
    <div class="page-header ph">
        <h2>Editing Reimbursement <br><small>department: {{object.department}} - payperiod: {{object.payperiod}}</small></h2>
        <a href="{% url 'mileage:delete_reimbursement' object.pk %}"><div id="del-reimbursement" class="btn btn-default">Delete Reimbursement</div></a></li>
        </br></br>
            <p>This form is for your personal vehicle usage only. Only include one programme per form. If you have
            mileage for multiple programmes you must submit a separate form for each programme.
    </p>
    </div>

    <div class="page-header pd">
        <
        <h2>Mileage Reimbursement Form</br>
        <small><b>Department:</b> {{object.department}} 
        <br><b>Title / Payperiod:</b> {{object.payperiod}}
        <br><b>Please Pay:</b> {{user.email}}</small></h2>
    </div>

    <div class="accordion" id="accordion2">
    <div class="accordion-group">
        <div class="accordion-heading ph">
            <a class="accordion-toggle collapsed ph" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
                <div class="btn btn-default ph">Add a Trip</div>
                <div id="print" class="btn btn-default ph">Print</div> 
                <br><br>
            </a>
        </div>
        <div id="collapseOne" class="accordion-body collapse">
            <div class="accordion-inner ph">
                <form action="" method="post"> {% csrf_token %}
                    {{form|crispy}}
                    <input type="submit" value="Add" />
                 </form>
            </div>
        </div>
    </div>
    </div>

    <h4>Mileage Trips</h4>
    {% if trips %}
    <div class="table-responsive">          
        <table class="table">
            <thead>
                <tr>
                    <td id="del">Delete</td>
                    <td>Date</td>
                    <td>Start</td>
                    <td>End</td>
                    <td>Distance</td>
                    <td id="hide">Description of Trip</td>
                </tr>
            </thead>
            <tbody>
            
            {% for trip in trips %}
                <tr>
                    <td id="del"><a href="{{trip.get_delete_url}}"> <i id="del-trip" class="fa fa-times"></i></a></td>
                    <td>{{ trip.created|date:"d/m/y" }}</td>
                    <td>{{ trip.trip_begin }}km</td>
                    <td>{{ trip.trip_end }}km</td>
                    <td>{{ trip.distance }}km</td>
                    <td id="hide"><div style="text-overflow: ellipsis;">{{ trip.description }}</div></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="position:fixed;bottom:0;">
        <table class="table table-hover">
                <tr>
                    <td>Total KM's Driven:</td>
                    <td>{{total_travelled.distance__sum}}kms</td>
                </tr>
                <tr>
                    <td>Total Amount Owed:</td>
                    <td>${{total_owed.amount_owed__sum}}</td>
                </tr>
                <tr>
                    <td>Approved By:</td>
                    <td></td>
                </tr>
        </table>
    </div>
    {% else %}
    <p>Add a trip!</p>
    {% endif %}
</div>

<script>
$( document ).ready(function() {
    $("#del-reimbursement").attr( "onclick", "return confirm('Are you sure you want to delete this?')" );
    $(".fa-times").each(function(i) {
        $(this).attr('onclick', "return confirm('Are you sure you want to delete this?')")
    })
});
$( "#print" ).click(function() {
  window.print()
});
</script>
{% endblock %}

admin_apps/templates/mileage/reimbursement_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block reimbursements %}
  {% for reimbursement in reimbursements %}
    <li><a href="{{reimbursement.get_absolute_url}}">{{ reimbursement.payperiod }}</a></li>
    {% endfor %}
{% endblock %}

{% block content %}
<div class="container" style="width: 100%;">
    <!--First block on the page to show general information -->
    <div class="page-header">
      <h1>New Reimbursement</h1>
    </div>

    <form action="" method="post">{% csrf_token %}
        {{ form.as_p }}
    <input type="submit" value="Create" />
    </form>
</div>

{% endblock %}

admin_apps/templates/mileage/reimbursement_list.html
{% extends "base.html" %}

<link rel="stylesheet" href="css/style.css"/>

{% block reimbursements %}
  {% for reimbursement in object_list %}
    <li><a href="{{reimbursement.get_absolute_url}}">{{ reimbursement.payperiod }}</a></li>
    {% endfor %}
{% endblock %}


{% block content %}
<div class="container" style="width: 100%;">
    <!--First block on the page to show general information -->
    <div class="page-header" style="padding-top:0px">
    <h1 >Instructions</h1>
    </div>
    <div class="col-lg-4">
      <h1 style="font-size:60px">1. <i class="fa fa-car"></i></h1>
      <p>Start a new reimbursement by clicking the following button or the one in the menu.</p>
      <a href="{% url 'mileage:create_reimbursement' %}"><div class="btn btn-default">New Reimbursement</div></a>
      <br></br>
      <p>You can also continue existing reimbursements by selecting them from the menu.</p>
    </div>
    <div class="col-lg-4">
      <h1 style="font-size:60px">2. <i class="fa fa-check-square-o"></i></h1>
      <p>Add new trips to the reimbursement by selecting 'New Trip'.</p>
    </div>
    <div class="col-lg-4">
      <h1 style="font-size:60px">3. <i class="fa fa-print"></i></h1>
      <p>Hit the 'Print' button to print off the form and give to your supervisor with your timesheet.</p>
    </div>
</div>
{% endblock %}